using PklCSharp.Generator.Declaration;
using PklCSharp.Generator.Utilities;

namespace PklGenerator.Tests.Declaration;

public class ClassDeclarationTests
{
    [Fact]
    public void ClassDeclarationGeneratesCorrectSourceCode()
    {
        var expectedSource = """
                             // <auto-generated />
                             namespace TestNamespace;
                             
                             public class ClassType
                             {
                                 public string Property1 { get; set; } = "Hello World";
                                 public GeneratedEnum? Property2 { get; set; }
                             }
                             
                             """;
        
        var testClass = new ClassDeclaration("ClassType", "TestNamespace");
        testClass.AddProperty(new Property("Property1", "string", Visibility.Public, false, "\"Hello World\""));
        testClass.AddProperty(new Property("Property2", "GeneratedEnum", Visibility.Public, true, null));

        var sourceText = testClass.ToSourceText();
        
        Assert.Equal(expectedSource, sourceText.ToString());
    }
}