using PklCSharp.Generator.Declaration;

namespace PklGenerator.Tests.Declaration;

public class EnumDeclarationTests
{
    [Fact]
    public void EnumDeclarationGeneratesCorrectSourceCode()
    {
        var expectedSource = """
                             // <auto-generated />
                             namespace TestNamespace;

                             public enum EnumType
                             {
                                 Member1,
                                 Member2,
                             }

                             """;
        
        var testEnum = new EnumDeclaration("EnumType", "TestNamespace");
        testEnum.AddMember("Member1");
        testEnum.AddMember("Member2");

        var sourceText = testEnum.ToSourceText();
        
        Assert.Equal(expectedSource, sourceText.ToString());
    }
}