name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        pklversion: [0.26.0,0.26.1,0.26.2,0.26.3]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install pkl
      uses: pkl-community/setup-pkl@v0
      with:
        pkl-version: ${{ matrix.pklversion }}
    - name: pkl cli version
      run: pkl --version
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Restore example dependencies
      working-directory: Examples
      run: dotnet restore
    - name: Build examples
      working-directory: Examples
      run: dotnet build --no-restore
